name: Greetings

on: [pull_request_target, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for your feedback and effort"
          pr-message: "Well, well, well"

      - uses: cinotify/github-action@main
        with:
          to: 'erik.hoelzel@posteo.de@example.com'
          subject: 'Breaking News - Breaking News'
          body: 'This is a notification from GitHub actions.'


